version: "3.6"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/portainer/data:/data
    environment:
      - TZ=${TZ}
  organizr:
    container_name: organizr
    restart: always
    image: lsiocommunity/organizr
    volumes:
      - ${USERDIR}/docker/organizr:/config
    ports:
      - "9500:80"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  transmission:
    container_name: transmission
    image: linuxserver/transmission
    restart: always
    ports:
    - "9091:9091"
    - "51413:51413"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${USERDIR}/docker/transmission:/config
      - ${USERDIR}/downloads:/downloads
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  sonarr:
    image: "linuxserver/sonarr"
    container_name: "sonarr"
    volumes:
      - ${USERDIR}/docker/sonarr:/config
      - ${USERDIR}/downloads/completed:/downloads
      - ${USERDIR}/media/tvshows:/tv
      - "/etc/localtime:/etc/localtime:ro"
      - ${USERDIR}/docker/shared:/shared
    ports:
        - "8989:8989"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  jackett:
    image: "linuxserver/jackett"
    container_name: "jackett"
    volumes:
      - ${USERDIR}/docker/jackett:/config
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "9117:9117"
    restart: always
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
  minidlna:
    image: vladgh/minidlna
    container_name: "minidlna"
    network_mode: "host"
    volumes:
      - "${USERDIR}/media/tvshows:/media/series"
      - "${USERDIR}/downloads/completed:/media/downloads"
    ports:
      - "8200:8200"
    environment:
      - "inotify=yes"
      - "notify_interval=900"
      - "MINIDLNA_FRIENDLY_NAME=Gundam"
      - "MINIDLNA_MEDIA_DIR_1=V,/media/series"
      - "MINIDLNA_MEDIA_DIR_2=V,/media/downloads"
    restart: always
